export const countryCodes = [
    { name: "Afghanistan", dial: "+93", code: "AF", flag: "🇦🇫" },
    { name: "Albania", dial: "+355", code: "AL", flag: "🇦🇱" },
    { name: "Algeria", dial: "+213", code: "DZ", flag: "🇩🇿" },
    { name: "Andorra", dial: "+376", code: "AD", flag: "🇦🇩" },
    { name: "Angola", dial: "+244", code: "AO", flag: "🇦🇴" },
    { name: "Antigua and Barbuda", dial: "+1-268", code: "AG", flag: "🇦🇬" },
    { name: "Argentina", dial: "+54", code: "AR", flag: "🇦🇷" },
    { name: "Armenia", dial: "+374", code: "AM", flag: "🇦🇲" },
    { name: "Australia", dial: "+61", code: "AU", flag: "🇦🇺" },
    { name: "Austria", dial: "+43", code: "AT", flag: "🇦🇹" },
    { name: "Azerbaijan", dial: "+994", code: "AZ", flag: "🇦🇿" },
    { name: "Bahamas", dial: "+1-242", code: "BS", flag: "🇧🇸" },
    { name: "Bahrain", dial: "+973", code: "BH", flag: "🇧🇭" },
    { name: "Bangladesh", dial: "+880", code: "BD", flag: "🇧🇩" },
    { name: "Barbados", dial: "+1-246", code: "BB", flag: "🇧🇧" },
    { name: "Belarus", dial: "+375", code: "BY", flag: "🇧🇾" },
    { name: "Belgium", dial: "+32", code: "BE", flag: "🇧🇪" },
    { name: "Belize", dial: "+501", code: "BZ", flag: "🇧🇿" },
    { name: "Benin", dial: "+229", code: "BJ", flag: "🇧🇯" },
    { name: "Bhutan", dial: "+975", code: "BT", flag: "🇧🇹" },
    { name: "Bolivia", dial: "+591", code: "BO", flag: "🇧🇴" },
    { name: "Bosnia and Herzegovina", dial: "+387", code: "BA", flag: "🇧🇦" },
    { name: "Botswana", dial: "+267", code: "BW", flag: "🇧🇼" },
    { name: "Brazil", dial: "+55", code: "BR", flag: "🇧🇷" },
    { name: "Brunei", dial: "+673", code: "BN", flag: "🇧🇳" },
    { name: "Bulgaria", dial: "+359", code: "BG", flag: "🇧🇬" },
    { name: "Burkina Faso", dial: "+226", code: "BF", flag: "🇧🇫" },
    { name: "Burundi", dial: "+257", code: "BI", flag: "🇧🇮" },
    { name: "Cambodia", dial: "+855", code: "KH", flag: "🇰🇭" },
    { name: "Cameroon", dial: "+237", code: "CM", flag: "🇨🇲" },
    { name: "Canada", dial: "+1", code: "CA", flag: "🇨🇦" },
    { name: "Cape Verde", dial: "+238", code: "CV", flag: "🇨🇻" },
    { name: "Central African Republic", dial: "+236", code: "CF", flag: "🇨🇫" },
    { name: "Chad", dial: "+235", code: "TD", flag: "🇹🇩" },
    { name: "Chile", dial: "+56", code: "CL", flag: "🇨🇱" },
    { name: "China", dial: "+86", code: "CN", flag: "🇨🇳" },
    { name: "Colombia", dial: "+57", code: "CO", flag: "🇨🇴" },
    { name: "Comoros", dial: "+269", code: "KM", flag: "🇰🇲" },
    { name: "Congo", dial: "+242", code: "CG", flag: "🇨🇬" },
    { name: "Costa Rica", dial: "+506", code: "CR", flag: "🇨🇷" },
    { name: "Croatia", dial: "+385", code: "HR", flag: "🇭🇷" },
    { name: "Cuba", dial: "+53", code: "CU", flag: "🇨🇺" },
    { name: "Cyprus", dial: "+357", code: "CY", flag: "🇨🇾" },
    { name: "Czech Republic", dial: "+420", code: "CZ", flag: "🇨🇿" },
    { name: "Denmark", dial: "+45", code: "DK", flag: "🇩🇰" },
    { name: "Djibouti", dial: "+253", code: "DJ", flag: "🇩🇯" },
    { name: "Dominica", dial: "+1-767", code: "DM", flag: "🇩🇲" },
    { name: "Dominican Republic", dial: "+1-809", code: "DO", flag: "🇩🇴" },
    { name: "Ecuador", dial: "+593", code: "EC", flag: "🇪🇨" },
    { name: "Egypt", dial: "+20", code: "EG", flag: "🇪🇬" },
    { name: "El Salvador", dial: "+503", code: "SV", flag: "🇸🇻" },
    { name: "Equatorial Guinea", dial: "+240", code: "GQ", flag: "🇬🇶" },
    { name: "Eritrea", dial: "+291", code: "ER", flag: "🇪🇷" },
    { name: "Estonia", dial: "+372", code: "EE", flag: "🇪🇪" },
    { name: "Eswatini", dial: "+268", code: "SZ", flag: "🇸🇿" },
    { name: "Ethiopia", dial: "+251", code: "ET", flag: "🇪🇹" },
    { name: "Fiji", dial: "+679", code: "FJ", flag: "🇫🇯" },
    { name: "Finland", dial: "+358", code: "FI", flag: "🇫🇮" },
    { name: "France", dial: "+33", code: "FR", flag: "🇫🇷" },
    { name: "Gabon", dial: "+241", code: "GA", flag: "🇬🇦" },
    { name: "Gambia", dial: "+220", code: "GM", flag: "🇬🇲" },
    { name: "Georgia", dial: "+995", code: "GE", flag: "🇬🇪" },
    { name: "Germany", dial: "+49", code: "DE", flag: "🇩🇪" },
    { name: "Ghana", dial: "+233", code: "GH", flag: "🇬🇭" },
    { name: "Greece", dial: "+30", code: "GR", flag: "🇬🇷" },
    { name: "Grenada", dial: "+1-473", code: "GD", flag: "🇬🇩" },
    { name: "Guatemala", dial: "+502", code: "GT", flag: "🇬🇹" },
    { name: "Guinea", dial: "+224", code: "GN", flag: "🇬🇳" },
    { name: "Guinea-Bissau", dial: "+245", code: "GW", flag: "🇬🇼" },
    { name: "Guyana", dial: "+592", code: "GY", flag: "🇬🇾" },
    { name: "Haiti", dial: "+509", code: "HT", flag: "🇭🇹" },
    { name: "Honduras", dial: "+504", code: "HN", flag: "🇭🇳" },
    { name: "Hungary", dial: "+36", code: "HU", flag: "🇭🇺" },
    { name: "Iceland", dial: "+354", code: "IS", flag: "🇮🇸" },
    { name: "India", dial: "+91", code: "IN", flag: "🇮🇳" },
    { name: "Indonesia", dial: "+62", code: "ID", flag: "🇮🇩" },
    { name: "Iran", dial: "+98", code: "IR", flag: "🇮🇷" },
    { name: "Iraq", dial: "+964", code: "IQ", flag: "🇮🇶" },
    { name: "Ireland", dial: "+353", code: "IE", flag: "🇮🇪" },
    { name: "Israel", dial: "+972", code: "IL", flag: "🇮🇱" },
    { name: "Italy", dial: "+39", code: "IT", flag: "🇮🇹" },
    { name: "Jamaica", dial: "+1-876", code: "JM", flag: "🇯🇲" },
    { name: "Japan", dial: "+81", code: "JP", flag: "🇯🇵" },
    { name: "Jordan", dial: "+962", code: "JO", flag: "🇯🇴" },
    { name: "Kazakhstan", dial: "+7", code: "KZ", flag: "🇰🇿" },
    { name: "Kenya", dial: "+254", code: "KE", flag: "🇰🇪" },
    { name: "Kiribati", dial: "+686", code: "KI", flag: "🇰🇮" },
    { name: "Kuwait", dial: "+965", code: "KW", flag: "🇰🇼" },
    { name: "Kyrgyzstan", dial: "+996", code: "KG", flag: "🇰🇬" },
    { name: "Laos", dial: "+856", code: "LA", flag: "🇱🇦" },
    { name: "Latvia", dial: "+371", code: "LV", flag: "🇱🇻" },
    { name: "Lebanon", dial: "+961", code: "LB", flag: "🇱🇧" },
    { name: "Lesotho", dial: "+266", code: "LS", flag: "🇱🇸" },
    { name: "Liberia", dial: "+231", code: "LR", flag: "🇱🇷" },
    { name: "Libya", dial: "+218", code: "LY", flag: "🇱🇾" },
    { name: "Liechtenstein", dial: "+423", code: "LI", flag: "🇱🇮" },
    { name: "Lithuania", dial: "+370", code: "LT", flag: "🇱🇹" },
    { name: "Luxembourg", dial: "+352", code: "LU", flag: "🇱🇺" },
    { name: "Madagascar", dial: "+261", code: "MG", flag: "🇲🇬" },
    { name: "Malawi", dial: "+265", code: "MW", flag: "🇲🇼" },
    { name: "Malaysia", dial: "+60", code: "MY", flag: "🇲🇾" },
    { name: "Maldives", dial: "+960", code: "MV", flag: "🇲🇻" },
    { name: "Mali", dial: "+223", code: "ML", flag: "🇲🇱" },
    { name: "Malta", dial: "+356", code: "MT", flag: "🇲🇹" },
    { name: "Marshall Islands", dial: "+692", code: "MH", flag: "🇲🇭" },
    { name: "Mauritania", dial: "+222", code: "MR", flag: "🇲🇷" },
    { name: "Mauritius", dial: "+230", code: "MU", flag: "🇲🇺" },
    { name: "Mexico", dial: "+52", code: "MX", flag: "🇲🇽" },
    { name: "Micronesia", dial: "+691", code: "FM", flag: "🇫🇲" },
    { name: "Moldova", dial: "+373", code: "MD", flag: "🇲🇩" },
    { name: "Monaco", dial: "+377", code: "MC", flag: "🇲🇨" },
    { name: "Mongolia", dial: "+976", code: "MN", flag: "🇲🇳" },
    { name: "Montenegro", dial: "+382", code: "ME", flag: "🇲🇪" },
    { name: "Morocco", dial: "+212", code: "MA", flag: "🇲🇦" },
    { name: "Mozambique", dial: "+258", code: "MZ", flag: "🇲🇿" },
    { name: "Myanmar", dial: "+95", code: "MM", flag: "🇲🇲" },
    { name: "Namibia", dial: "+264", code: "NA", flag: "🇳🇦" },
    { name: "Nauru", dial: "+674", code: "NR", flag: "🇳🇷" },
    { name: "Nepal", dial: "+977", code: "NP", flag: "🇳🇵" },
    { name: "Netherlands", dial: "+31", code: "NL", flag: "🇳🇱" },
    { name: "New Zealand", dial: "+64", code: "NZ", flag: "🇳🇿" },
    { name: "Nicaragua", dial: "+505", code: "NI", flag: "🇳🇮" },
    { name: "Niger", dial: "+227", code: "NE", flag: "🇳🇪" },
    { name: "Nigeria", dial: "+234", code: "NG", flag: "🇳🇬" },
    { name: "North Korea", dial: "+850", code: "KP", flag: "🇰🇵" },
    { name: "North Macedonia", dial: "+389", code: "MK", flag: "🇲🇰" },
    { name: "Norway", dial: "+47", code: "NO", flag: "🇳🇴" },
    { name: "Oman", dial: "+968", code: "OM", flag: "🇴🇲" },
    { name: "Pakistan", dial: "+92", code: "PK", flag: "🇵🇰" },
    { name: "Palau", dial: "+680", code: "PW", flag: "🇵🇼" },
    { name: "Panama", dial: "+507", code: "PA", flag: "🇵🇦" },
    { name: "Papua New Guinea", dial: "+675", code: "PG", flag: "🇵🇬" },
    { name: "Paraguay", dial: "+595", code: "PY", flag: "🇵🇾" },
    { name: "Peru", dial: "+51", code: "PE", flag: "🇵🇪" },
    { name: "Philippines", dial: "+63", code: "PH", flag: "🇵🇭" },
    { name: "Poland", dial: "+48", code: "PL", flag: "🇵🇱" },
    { name: "Portugal", dial: "+351", code: "PT", flag: "🇵🇹" },
    { name: "Qatar", dial: "+974", code: "QA", flag: "🇶🇦" },
    { name: "Romania", dial: "+40", code: "RO", flag: "🇷🇴" },
    { name: "Russia", dial: "+7", code: "RU", flag: "🇷🇺" },
    { name: "Rwanda", dial: "+250", code: "RW", flag: "🇷🇼" },
    { name: "Saint Kitts and Nevis", dial: "+1-869", code: "KN", flag: "🇰🇳" },
    { name: "Saint Lucia", dial: "+1-758", code: "LC", flag: "🇱🇨" },
    { name: "Saint Vincent and the Grenadines", dial: "+1-784", code: "VC", flag: "🇻🇨" },
    { name: "Samoa", dial: "+685", code: "WS", flag: "🇼🇸" },
    { name: "San Marino", dial: "+378", code: "SM", flag: "🇸🇲" },
    { name: "Sao Tome and Principe", dial: "+239", code: "ST", flag: "🇸🇹" },
    { name: "Saudi Arabia", dial: "+966", code: "SA", flag: "🇸🇦" },
    { name: "Senegal", dial: "+221", code: "SN", flag: "🇸🇳" },
    { name: "Serbia", dial: "+381", code: "RS", flag: "🇷🇸" },
    { name: "Seychelles", dial: "+248", code: "SC", flag: "🇸🇨" },
    { name: "Sierra Leone", dial: "+232", code: "SL", flag: "🇸🇱" },
    { name: "Singapore", dial: "+65", code: "SG", flag: "🇸🇬" },
    { name: "Slovakia", dial: "+421", code: "SK", flag: "🇸🇰" },
    { name: "Slovenia", dial: "+386", code: "SI", flag: "🇸🇮" },
    { name: "Solomon Islands", dial: "+677", code: "SB", flag: "🇸🇧" },
    { name: "Somalia", dial: "+252", code: "SO", flag: "🇸🇴" },
    { name: "South Africa", dial: "+27", code: "ZA", flag: "🇿🇦" },
    { name: "South Korea", dial: "+82", code: "KR", flag: "🇰🇷" },
    { name: "South Sudan", dial: "+211", code: "SS", flag: "🇸🇸" },
    { name: "Spain", dial: "+34", code: "ES", flag: "🇪🇸" },
    { name: "Sri Lanka", dial: "+94", code: "LK", flag: "🇱🇰" },
    { name: "Sudan", dial: "+249", code: "SD", flag: "🇸🇩" },
    { name: "Suriname", dial: "+597", code: "SR", flag: "🇸🇷" },
    { name: "Sweden", dial: "+46", code: "SE", flag: "🇸🇪" },
    { name: "Switzerland", dial: "+41", code: "CH", flag: "🇨🇭" },
    { name: "Syria", dial: "+963", code: "SY", flag: "🇸🇾" },
    { name: "Taiwan", dial: "+886", code: "TW", flag: "🇹🇼" },
    { name: "Tajikistan", dial: "+992", code: "TJ", flag: "🇹🇯" },
    { name: "Tanzania", dial: "+255", code: "TZ", flag: "🇹🇿" },
    { name: "Thailand", dial: "+66", code: "TH", flag: "🇹🇭" },
    { name: "Togo", dial: "+228", code: "TG", flag: "🇹🇬" },
    { name: "Tonga", dial: "+676", code: "TO", flag: "🇹🇴" },
    { name: "Trinidad and Tobago", dial: "+1-868", code: "TT", flag: "🇹🇹" },
    { name: "Tunisia", dial: "+216", code: "TN", flag: "🇹🇳" },
    { name: "Turkey", dial: "+90", code: "TR", flag: "🇹🇷" },
    { name: "Turkmenistan", dial: "+993", code: "TM", flag: "🇹🇲" },
    { name: "Tuvalu", dial: "+688", code: "TV", flag: "🇹🇻" },
    { name: "Uganda", dial: "+256", code: "UG", flag: "🇺🇬" },
    { name: "Ukraine", dial: "+380", code: "UA", flag: "🇺🇦" },
    { name: "United Arab Emirates", dial: "+971", code: "AE", flag: "🇦🇪" },
    { name: "United Kingdom", dial: "+44", code: "GB", flag: "🇬🇧" },
    { name: "United States", dial: "+1", code: "US", flag: "🇺🇸" },
    { name: "Uruguay", dial: "+598", code: "UY", flag: "🇺🇾" },
    { name: "Uzbekistan", dial: "+998", code: "UZ", flag: "🇺🇿" },
    { name: "Vanuatu", dial: "+678", code: "VU", flag: "🇻🇺" },
    { name: "Venezuela", dial: "+58", code: "VE", flag: "🇻🇪" },
    { name: "Vietnam", dial: "+84", code: "VN", flag: "🇻🇳" },
    { name: "Yemen", dial: "+967", code: "YE", flag: "🇾🇪" },
    { name: "Zambia", dial: "+260", code: "ZM", flag: "🇿🇲" },
    { name: "Zimbabwe", dial: "+263", code: "ZW", flag: "🇿🇼" }
];
